# Generated by Django 2.1.2 on 2018-11-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='release_date',
        ),
    ]
