# Generated by Django 2.1.2 on 2018-12-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181211_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(default='book.png', upload_to='book_pics'),
        ),
    ]
